
import React from "react";
import {
  X,
  Users,
  MousePointer,
  Bell,
  Slack,
  Play,
  MonitorPlay,
  Shield,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { trackCTAClick } from '@/lib/analytics';

interface CEOUnloadSystemModalContentProps {
  onClose: () => void;
}

const CEOUnloadSystemModalContent: React.FC<
  CEOUnloadSystemModalContentProps
> = ({ onClose }) => {

  const handleCTAClick = () => {
    trackCTAClick('Book Your Strategy Call', 'ceo_unload_system_modal');
    window.open('https://calendly.com/tdiaagency/30min?month=2025-06', '_blank');
  };
  
  return (
    <div className="relative w-full max-w-[100vw] h-[90vh] max-h-screen overflow-y-auto rounded-xl bg-gradient-to-br from-[#0a0b1d] via-[#1a1b2e] to-[#0f172a] text-white mx-2 sm:mx-4">

      {/* ───── Whole‑page Scrollable Area (header → footer) ───── */}
      <ScrollArea className="h-full">
        {/* ───── Header ───── */}
        <header className="border-b border-white/10 px-4 sm:px-6 md:px-8 lg:px-12 pb-6 sm:pb-8 pt-16 sm:pt-20">
          <div className="text-center">
            <div className="mb-4 sm:mb-6 inline-flex items-center gap-2 sm:gap-3">
              <div className="flex h-12 w-12 sm:h-16 sm:w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-gray-700 to-gray-900">
                <Users className="h-6 w-6 sm:h-8 sm:w-8 text-white" />
              </div>
              <h1 className="bg-gradient-to-r from-white to-gray-300 bg-clip-text text-2xl sm:text-3xl md:text-4xl lg:text-6xl font-bold text-transparent leading-tight">
                CEO Unload System™
              </h1>
            </div>
            <p className="mb-3 sm:mb-4 text-lg sm:text-xl md:text-2xl text-gray-300">
              "For founders who want the results, not the overwhelm."
            </p>
            <div className="inline-block rounded-lg border border-red-500/30 bg-red-500/20 px-4 sm:px-6 py-2 sm:py-3">
              <p className="text-sm sm:text-base font-medium text-red-300">
                Pain: "I'm overloaded and can't manage everything myself."
              </p>
            </div>
          </div>
        </header>

        {/* ───── Main Content ───── */}
        <main className="mx-auto max-w-7xl space-y-6 sm:space-y-8 px-4 sm:px-6 md:px-8 lg:px-12 py-8 sm:py-12">
          {/* ███ Module 1 — 1‑Click Decision Portal ███ */}
          <section className="rounded-2xl border border-blue-500/20 bg-gradient-to-r from-blue-900/20 to-blue-800/10 p-4 sm:p-6 md:p-8">
            <div className="flex flex-col sm:flex-row items-start gap-4 sm:gap-6">
              <div className="flex h-12 w-12 sm:h-16 sm:w-16 flex-shrink-0 items-center justify-center rounded-xl bg-blue-500/20">
                <MousePointer className="h-6 w-6 sm:h-8 sm:w-8 text-blue-400" />
              </div>
              <div className="flex-1 min-w-0">
                <h3 className="mb-2 sm:mb-3 text-xl sm:text-2xl font-bold text-white">
                  1‑Click Decision Portal
                </h3>
                <p className="mb-4 sm:mb-6 text-base sm:text-lg text-gray-300 leading-relaxed">
                  Decide in seconds, not meetings. Approve or reject campaigns
                  with a single click.
                </p>

                <div className="mb-3 sm:mb-4 rounded-lg bg-white/5 p-4 sm:p-6">
                  <p className="mb-2 sm:mb-3 text-sm sm:text-base font-medium text-blue-300">
                    Stay in control without being overwhelmed.
                  </p>
                  <p className="mb-3 sm:mb-4 text-xs sm:text-sm text-gray-300">
                    Our team handles the chaos, you just validate. No Slack
                    threads, no meetings, no stress.
                  </p>

                  {/* Mock Decision card */}
                  <div className="rounded-lg border border-blue-500/20 bg-gradient-to-br from-blue-950/50 to-blue-900/30 p-3 sm:p-4">
                    <div className="mb-2 sm:mb-3 flex items-center justify-between">
                      <span className="text-xs sm:text-sm font-medium text-white">
                        Campaign: Black Friday Video Ad
                      </span>
                      <span className="text-xs text-blue-300">
                        Generated by TDIA
                      </span>
                    </div>
                    <div className="flex gap-2 sm:gap-3">
                      <button className="flex-1 rounded-lg bg-green-600 px-3 sm:px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-green-700 min-h-[36px]">
                        Go
                      </button>
                      <button className="flex-1 rounded-lg bg-red-600 px-3 sm:px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-red-700 min-h-[36px]">
                        No‑Go
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* ███ Module 2 — Real‑Time Alerts ███ */}
          <section className="rounded-2xl border border-green-500/20 bg-gradient-to-r from-green-900/20 to-green-800/10 p-4 sm:p-6 md:p-8">
            <div className="flex flex-col sm:flex-row items-start gap-4 sm:gap-6">
              <div className="flex h-12 w-12 sm:h-16 sm:w-16 flex-shrink-0 items-center justify-center rounded-xl bg-green-500/20">
                <Bell className="h-6 w-6 sm:h-8 sm:w-8 text-green-400" />
              </div>
              <div className="flex-1 min-w-0">
                <h3 className="mb-2 sm:mb-3 text-xl sm:text-2xl font-bold text-white">
                  Real‑Time Alerts. Only When It Matters.
                </h3>
                <p className="mb-4 sm:mb-6 text-base sm:text-lg text-gray-300 leading-relaxed">
                  Get instant anomaly alerts — smart Slack notifications with
                  zero noise.
                </p>

                <div className="mb-3 sm:mb-4 rounded-lg bg-white/5 p-4 sm:p-6">
                  <p className="mb-2 sm:mb-3 text-sm sm:text-base font-medium text-green-300">
                    Protection without constant monitoring.
                  </p>
                  <p className="mb-3 sm:mb-4 text-xs sm:text-sm text-gray-300">
                    Our team auto‑prioritizes and fixes issues in under 48 h.
                  </p>

                  {/* Mock Slack alert */}
                  <div className="rounded-lg border border-green-500/20 bg-gradient-to-br from-green-950/50 to-green-900/30 p-3 sm:p-4">
                    <div className="mb-2 flex items-center gap-2 sm:gap-3">
                      <Slack className="h-4 w-4 sm:h-5 sm:w-5 text-green-400" />
                      <span className="text-xs sm:text-sm font-medium text-green-300">
                        TDIA Alert System
                      </span>
                      <span className="text-xs text-gray-400">2:34 PM</span>
                    </div>
                    <div className="rounded border border-orange-500/30 bg-orange-500/20 p-2 sm:p-3">
                      <p className="text-xs sm:text-sm font-medium text-orange-300">
                        Meta CPA +32 % detected
                      </p>
                      <p className="mt-1 text-xs text-gray-300">
                        Triggered intervention protocol. Team investigating.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* ███ Module 3 — Weekly Recap ███ */}
          <section className="rounded-2xl border border-purple-500/20 bg-gradient-to-r from-purple-900/20 to-purple-800/10 p-4 sm:p-6 md:p-8">
            <div className="flex flex-col sm:flex-row items-start gap-4 sm:gap-6">
              <div className="flex h-12 w-12 sm:h-16 sm:w-16 flex-shrink-0 items-center justify-center rounded-xl bg-purple-500/20">
                <MonitorPlay className="h-6 w-6 sm:h-8 sm:w-8 text-purple-400" />
              </div>
              <div className="flex-1 min-w-0">
                <h3 className="mb-2 sm:mb-3 text-xl sm:text-2xl font-bold text-white">
                  Weekly Recap — No Meetings Required
                </h3>
                <p className="mb-4 sm:mb-6 text-base sm:text-lg text-gray-300 leading-relaxed">
                  A Friday Loom video covering results, creative performance,
                  and next steps.
                </p>

                <div className="mb-3 sm:mb-4 rounded-lg bg-white/5 p-4 sm:p-6">
                  <p className="mb-2 sm:mb-3 text-sm sm:text-base font-medium text-purple-300">
                    Feels like a strategic partner, not an agency.
                  </p>
                  <p className="mb-3 sm:mb-4 text-xs sm:text-sm text-gray-300">
                    Watch on your own time, understand the strategy, and stay
                    confident in your trajectory.
                  </p>

                  {/* Mock Loom card */}
                  <div className="rounded-lg border border-purple-500/20 bg-gradient-to-br from-purple-950/50 to-purple-900/30 p-3 sm:p-4">
                    <div className="mb-2 sm:mb-3 flex items-center gap-2 sm:gap-3">
                      <div className="flex h-8 w-8 sm:h-10 sm:w-10 items-center justify-center rounded-full bg-purple-600">
                        <Play className="h-4 w-4 sm:h-5 sm:w-5 text-white" />
                      </div>
                      <div className="min-w-0 flex-1">
                        <p className="text-xs sm:text-sm font-medium text-white">
                          Weekly Strategy Recap – Week 47
                        </p>
                        <p className="text-xs text-purple-300">
                          by Sarah, TDIA Strategist • 12:30
                        </p>
                      </div>
                    </div>
                    <p className="text-xs text-gray-300">
                      "ROAS up 23 %, new creative variants testing well..."
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* ███ Bonus Module — CEO Onboarding ███ */}
          <section className="rounded-2xl border border-orange-500/20 bg-gradient-to-r from-orange-900/20 to-orange-800/10 p-4 sm:p-6 md:p-8">
            <div className="flex flex-col sm:flex-row items-start gap-4 sm:gap-6">
              <div className="flex h-12 w-12 sm:h-16 sm:w-16 flex-shrink-0 items-center justify-center rounded-xl bg-orange-500/20">
                <Shield className="h-6 w-6 sm:h-8 sm:w-8 text-orange-400" />
              </div>
              <div className="flex-1 min-w-0">
                <h3 className="mb-2 sm:mb-3 text-xl sm:text-2xl font-bold text-white">
                  BONUS: CEO Onboarding
                </h3>
                <p className="text-base sm:text-lg text-gray-300 leading-relaxed">
                  A 15‑minute Loom explaining our analysis framework so you
                  trust the system — no marketing degree required.
                </p>
              </div>
            </div>
          </section>

          {/* ███ Result Block ███ */}
          <section className="rounded-2xl border border-emerald-500/30 bg-gradient-to-r from-emerald-500/20 to-teal-500/20 p-4 sm:p-6 md:p-8 text-center">
            <h3 className="mb-3 sm:mb-4 text-xl sm:text-2xl font-bold text-emerald-300">
              Business Result
            </h3>
            <p className="text-lg sm:text-xl leading-relaxed text-white">
              "Live dashboard, AI alerts, async updates, and a micro‑team
              delegated by TDIA = less time, more growth."
            </p>
          </section>
        </main>

        {/* ───── CTA Footer (scrolls into view) ───── */}
        <footer className="space-y-4 border-t border-white/10 bg-gradient-to-t from-black/80 to-transparent px-4 sm:px-6 md:px-8 lg:px-12 py-8 sm:py-12 text-center backdrop-blur-sm">
          <div className="flex flex-col justify-center gap-4 sm:flex-row">
          </div>
          <Button onClick={handleCTAClick} className="bg-gradient-to-r from-gray-700 to-gray-800 px-6 sm:px-8 py-3 sm:py-4 text-base sm:text-lg font-medium text-white transition-colors hover:from-gray-800 hover:to-gray-900 min-h-[44px]">
            Get My Strategic Partner
          </Button>
        </footer>
      </ScrollArea>
    </div>
  );
};

export default CEOUnloadSystemModalContent;
