// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lukcwgedisgdemugsqoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1a2N3Z2VkaXNnZGVtdWdzcW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMjYwNzAsImV4cCI6MjA2MzgwMjA3MH0.3V4y_LihRcnTTbVzMPU6MB_GuT0QlrAdj-PRL96eOUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);